@startuml AppClassDiagram

skinparam classAttributeIconSize 0

abstract class Alarm {
    +int iterative
    +DateTime time
    +APIData data
}

class WeatherAlarm {
    +int iterative
    +DateTime time
    +WeatherAPIDAO data
}

class TransportationAlarm {
    +int iterative
    +DateTime time
    +TransportationAPIDAO data
}


class WeatherAPIDAO {
    +WeatherAPIDTO dto
    +void update(double latitude, double longitude)
}

class CurrentWeatherAPIDataDTO {
    +WeatherState weatherState
    +PrecipitationType precipitationType
    +double temperature
    +double PrecipitatePercent
    +double Precipitation
    +double highestTemperature
    +double lowestTemperature
    +void update(double latitude, double longitude)
}

class ForecastWeatherAPIDataDTO {
    +List<WeatherState> weatherStates
    +List<PrecipitationType> precipitationTypes
    +List<double> highestTemperatures
    +List<double> lowestTemperatures
    +void update(double latitude, double longitude)
}

enum WeatherState {
    +SUN
    +PARTLY_SUN // 아직 잘 모름
    +PARTLY_CLOUD
    +CLOUD
}

enum PrecipitationType {
    +NONE
    +RAIN
    +RAIN_AND_SNOW
    +SNOW
    +_
    +RAINDROP
    +RAINDROP_AND_SNOW
    +SNOWFLAKE
}





class TransportationAPIDAO {
    +TransportAPIDTO dto
    +void update(???)
}

class SubwaySearchAPIDataDTO {
    +String stationName
    +String lineName
    +String nextStationName
    +String msg1
    +String msg2
    +void update(String stationName, String lineName, bool is상행)
}

class SubwayArrivalAPIDataDTO {

}

class BusAPIData {
    ' +int leftTime
    ' +int busId
    ' +String lineName
    ' +int stationId
    ' +void getCurrData()
}

TransportationAPIDAO <-- SubwaySearchAPIDataDTO
TransportationAPIDAO <-- SubwayArrivalAPIDataDTO
TransportationAPIDAO <-- BusAPIData


TransportationAlarm *-- TransportationAPIDAO


WeatherAlarm *-- WeatherAPIDAO
Alarm <-- WeatherAlarm
Alarm <-- TransportationAlarm

WeatherAPIDAO <-- CurrentWeatherAPIDataDTO
WeatherAPIDAO <-- ForecastWeatherAPIDataDTO

CurrentWeatherAPIDataDTO <-- WeatherState
CurrentWeatherAPIDataDTO <-- PrecipitationType
ForecastWeatherAPIDataDTO <-- WeatherState
ForecastWeatherAPIDataDTO <-- PrecipitationType




@enduml