@startuml app-server-api
activate 앱
앱 -> 서버 : API 데이터 요청
activate 서버
note over 서버 : API 인자 전달방식: 미정
서버 -> 서버 : API 코드 실행 (Python)
서버 ->> 앱 : 결과값 전달
deactivate 서버
앱 ->> 앱 : 해당 정보 TTS 알림
deactivate 앱
@enduml

'https://raw.githubusercontent.com/Team-Kelly/Requirements/main/uml/sequence/app-server-api.puml